/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemon_ac1;

import java.util.Random;


public class Batalha extends javax.swing.JFrame {

    private int play1;
            
    public Batalha(Integer play1) {
        this.play1 = play1;
        initComponents();
        
        myplayer();
    }

    public Batalha() {       
    }

    private void myplayer(){
        
        switch (play1){
            case 1:
                zubat.setVisible(true);
                arbok.setVisible(false);
                gengar.setVisible(false);
                raichu.setVisible(false);
                pzubat.setVisible(true);
                Empate.setVisible(false);
                Perdedor.setVisible(false);
                Vencedor.setVisible(false);
                parbok.setVisible(false);
                pgengar.setVisible(false);
                praichu.setVisible(false);
                break;
                 case 2:
                zubat.setVisible(false);
                arbok.setVisible(false);
                gengar.setVisible(false);
                raichu.setVisible(true);
                praichu.setVisible(true);
                Empate.setVisible(false);
                Perdedor.setVisible(false);
                Vencedor.setVisible(false);
                pzubat.setVisible(false);
                pgengar.setVisible(false);
                parbok.setVisible(false);
                break;
                 case 3:
                zubat.setVisible(false);
                arbok.setVisible(false);
                gengar.setVisible(true);
                raichu.setVisible(false);
                pgengar.setVisible(true);
                Empate.setVisible(false);
                Perdedor.setVisible(false);
                Vencedor.setVisible(false);
                pzubat.setVisible(false);
                parbok.setVisible(false);
                praichu.setVisible(false);
                break;
                 case 4:
                zubat.setVisible(false);
                arbok.setVisible(true);
                gengar.setVisible(false);
                raichu.setVisible(false);
                parbok.setVisible(true);
                Empate.setVisible(false);
                Perdedor.setVisible(false);
                Vencedor.setVisible(false);
                pzubat.setVisible(false);
                pgengar.setVisible(false);
                praichu.setVisible(false);
                break;
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zubat = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mypoke = new javax.swing.JTextField();
        arbok = new javax.swing.JLabel();
        raichu = new javax.swing.JLabel();
        gengar = new javax.swing.JLabel();
        parbok = new javax.swing.JTextField();
        pzubat = new javax.swing.JTextField();
        pgengar = new javax.swing.JTextField();
        praichu = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        Pinimigo = new javax.swing.JTextField();
        battle = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        Empate = new javax.swing.JTextField();
        Vencedor = new javax.swing.JTextField();
        Perdedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(440, 330));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        zubat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon_ac1/kisspng-golbat-pokmon-go-pokdex-zubat-5baa211e3a9d11.4570849115378762542401 (5).png"))); // NOI18N
        getContentPane().add(zubat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon_ac1/download (3).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 80, 80));

        mypoke.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mypoke.setText("Você");
        mypoke.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        mypoke.setEnabled(false);
        mypoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mypokeActionPerformed(evt);
            }
        });
        getContentPane().add(mypoke, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 40, 30));

        arbok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon_ac1/png-clipart-arbok-pokemon-pokemon-black-white-ekans-dream-world-pokemon-purple-violet (1).png"))); // NOI18N
        arbok.setText("arbok");
        getContentPane().add(arbok, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 80, -1));

        raichu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon_ac1/158-1587845_canandaluz-team-raichu-png (1).png"))); // NOI18N
        getContentPane().add(raichu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 80, -1));

        gengar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon_ac1/download (2).png"))); // NOI18N
        getContentPane().add(gengar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 80, -1));

        parbok.setText("98");
        getContentPane().add(parbok, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 20, -1));

        pzubat.setText("55");
        pzubat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pzubatActionPerformed(evt);
            }
        });
        getContentPane().add(pzubat, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 20, -1));

        pgengar.setText("120");
        getContentPane().add(pgengar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 20, -1));

        praichu.setText("86");
        getContentPane().add(praichu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 20, -1));

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Inimigo");
        jTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField1.setEnabled(false);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 50, 30));

        Pinimigo.setText("?");
        Pinimigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinimigoActionPerformed(evt);
            }
        });
        getContentPane().add(Pinimigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 30, -1));

        battle.setText("battle");
        battle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                battleActionPerformed(evt);
            }
        });
        getContentPane().add(battle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 100, -1));

        jTextField2.setText("Poder");
        jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField2.setEnabled(false);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 50, -1));

        jTextField3.setText("Poder");
        jTextField3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField3.setEnabled(false);
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 50, -1));

        Empate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Empate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Empate.setText("Empate");
        Empate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpateActionPerformed(evt);
            }
        });
        getContentPane().add(Empate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 110, 80));

        Vencedor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Vencedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Vencedor.setText("Vencedor");
        Vencedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VencedorActionPerformed(evt);
            }
        });
        getContentPane().add(Vencedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 110, 80));

        Perdedor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Perdedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Perdedor.setText("Perdedor");
        Perdedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerdedorActionPerformed(evt);
            }
        });
        getContentPane().add(Perdedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 110, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon_ac1/papel-de-parede-infantil-pokemon-lisiane-sousa-papel-de-parede-de-fotografia (1) (2).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void mypokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mypokeActionPerformed
        
    }//GEN-LAST:event_mypokeActionPerformed

    private void pzubatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pzubatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pzubatActionPerformed

    private void PinimigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinimigoActionPerformed
           
    }//GEN-LAST:event_PinimigoActionPerformed

    private void battleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_battleActionPerformed
        int pinimigo = new Random().nextInt(125) +1;
        Pinimigo.setText(Integer.toOctalString(pinimigo));
        switch (play1){
            case 1:
                if(55 < pinimigo){
                    Perdedor.setVisible(true);
                }else if(55 > pinimigo){
                    Vencedor.setVisible(true);
                }else{
                    Empate.setVisible(true);
                }
                break;
                case 2:
                if(86 < pinimigo){
                    Perdedor.setVisible(true);
                }else if(86 > pinimigo){
                    Vencedor.setVisible(true);
                }else{
                    Empate.setVisible(true);
                }
                break;
                case 3:
                if(120 < pinimigo){
                    Perdedor.setVisible(true);
                }else if(120 > pinimigo){
                    Vencedor.setVisible(true);
                }else{
                    Empate.setVisible(true);
                }
                break;
                case 4:
                if(98 < pinimigo){
                    Perdedor.setVisible(true);
                }else if(98 > pinimigo){
                    Vencedor.setVisible(true);
                }else{
                    Empate.setVisible(true);
                }
                break;
        }
        
    }//GEN-LAST:event_battleActionPerformed

    private void EmpateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpateActionPerformed

    private void VencedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VencedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VencedorActionPerformed

    private void PerdedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerdedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerdedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Batalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Batalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Batalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Batalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Batalha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Empate;
    private javax.swing.JTextField Perdedor;
    private javax.swing.JTextField Pinimigo;
    private javax.swing.JTextField Vencedor;
    private javax.swing.JLabel arbok;
    private javax.swing.JButton battle;
    private javax.swing.JLabel gengar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField mypoke;
    private javax.swing.JTextField parbok;
    private javax.swing.JTextField pgengar;
    private javax.swing.JTextField praichu;
    private javax.swing.JTextField pzubat;
    private javax.swing.JLabel raichu;
    private javax.swing.JLabel zubat;
    // End of variables declaration//GEN-END:variables
}
