/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemon_ac1;

/**
 *
 * @author 55159
 */
public class escolhapoke extends javax.swing.JFrame {
    
    private Integer myplayer;
    
    public escolhapoke() {
        initComponents();
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gengar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        zubat = new javax.swing.JButton();
        arbok = new javax.swing.JButton();
        raichu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gengar.setText("Gengar");
        gengar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gengarActionPerformed(evt);
            }
        });
        getContentPane().add(gengar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        jTextField1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Escolha o Pokemon Para Jogar");
        jTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 220, -1));

        zubat.setText("Zubat");
        zubat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zubatActionPerformed(evt);
            }
        });
        getContentPane().add(zubat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        arbok.setText("Arbok");
        arbok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arbokActionPerformed(evt);
            }
        });
        getContentPane().add(arbok, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        raichu.setText("Raichu");
        raichu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raichuActionPerformed(evt);
            }
        });
        getContentPane().add(raichu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon_ac1/kisspng-golbat-pokmon-go-pokdex-zubat-5baa211e3a9d11.4570849115378762542401 (5).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, 90));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon_ac1/png-clipart-arbok-pokemon-pokemon-black-white-ekans-dream-world-pokemon-purple-violet (1).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon_ac1/download (2).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon_ac1/158-1587845_canandaluz-team-raichu-png (1).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon_ac1/papel-de-parede-infantil-pokemon-lisiane-sousa-papel-de-parede-de-fotografia (1) (2).jpg"))); // NOI18N
        jLabel1.setText("fundo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zubatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zubatActionPerformed
      
       new Batalha(1).setVisible(true);
        dispose();
    }//GEN-LAST:event_zubatActionPerformed

    private void raichuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raichuActionPerformed
      
        new Batalha(2).setVisible(true);
        dispose();
    }//GEN-LAST:event_raichuActionPerformed

    private void gengarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gengarActionPerformed
       
        new Batalha(3).setVisible(true);
        dispose();
    }//GEN-LAST:event_gengarActionPerformed

    private void arbokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arbokActionPerformed
      
        new Batalha(4).setVisible(true);
        dispose();
    }//GEN-LAST:event_arbokActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(escolhapoke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(escolhapoke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(escolhapoke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(escolhapoke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new escolhapoke().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arbok;
    private javax.swing.JButton gengar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton raichu;
    private javax.swing.JButton zubat;
    // End of variables declaration//GEN-END:variables
}
